/* config.h.  Generated by configure.  */
/* define HAVE_IN_ADDR_T if your system has a typedef for in_addr_t */
#define HAVE_IN_ADDR_T 1

/* define HAVE_U_INT32_T if your system has a typedef for u_int32_t */
#define HAVE_U_INT32_T 1

/* define HAVE_TIMESTAMP_IOCTL if your system has an ioctl for getting
	packet timestamps (Linux) */
/* #undef HAVE_TIMESTAMP_IOCTL */

/* define HAVE_SO_TIMESTAMP if your system has an SO_TIMESTAMP for getting
	packet timestamps (FreeBSD) */
#define HAVE_SO_TIMESTAMP 1

/* define on systems with sched.h */
#define HAVE_SCHED_H 1

/* define on systems with sys/mman.h */
#define HAVE_SYS_MMAN_H 1

/* define on systems with gnome.h */
/* #undef HAVE_GNOME_H */
